'use client'
import { useEffect, useMemo, useState } from 'react'
type Product={sku:string;brand:string;family:string;description:string;source:string;image:string;gender:string;availability:string}
const products:Product[]=[
{sku:'TASAC3521',brand:'Montescano',family:'MONTESCANO',description:'Acero sólido · caballero',source:'CATALOGO IMAGENES 01 MONTESCANO 0826 SF.pdf · p. 1',image:'/catalogo/montescano-page1.png',gender:'Caballero',availability:'Consultar disponibilidad'},
{sku:'VC4403G',brand:'Vizanti',family:'VIZANTI',description:'Reloj Vizanti para caballero',source:'CATALOGO IMAGENES 02 VIZANTI 0426 SF.pdf · p. 1',image:'/catalogo/montescano-page1.png',gender:'Caballero',availability:'Consultar disponibilidad'},
{sku:'VKO2247MV',brand:'Vizanti Kids',family:'KIDS',description:'Reloj infantil documentado',source:'CATALOGO IMAGENES 03 VIZANTI KIDS 0426 SF.pdf · p. 1',image:'/catalogo/montescano-page1.png',gender:'Niños',availability:'Consultar disponibilidad'},
{sku:'VSW54N',brand:'Vizanti',family:'SMART WATCH',description:'Smart Watch · color negro',source:'CATALOGO IMAGENES 04 VIZANTI SMART WATCH 0426 SF.pdf · p. 1',image:'/catalogo/smartwatch-page1.png',gender:'Unisex',availability:'Consultar disponibilidad'},
{sku:'SETVC2202',brand:'Vizanti',family:'SETS',description:'Set de regalo documentado',source:'CATALOGO IMAGENES 05 SETS Montescano y Vizanti 0526 SF.pdf · p. 8',image:'/catalogo/montescano-page1.png',gender:'Caballero',availability:'Consultar disponibilidad'},
{sku:'03NDBP',brand:'Montescano',family:'PLUMAS',description:'Pluma Montescano',source:'CATALOGO IMAGENES 06 PLUMAS MONTESCANO SF.pdf · p. 1',image:'/catalogo/montescano-page1.png',gender:'Caballero',availability:'Consultar disponibilidad'}]
const families=[['TODOS','399'],['MONTESCANO','135'],['VIZANTI','144'],['KIDS','58'],['SMART WATCH','4'],['SETS','45'],['PLUMAS','13']]
export default function Home(){
 const [active,setActive]=useState('TODOS'),[query,setQuery]=useState(''),[gender,setGender]=useState('Todos'),[quick,setQuick]=useState<Product|null>(null),[menu,setMenu]=useState(false),[slide,setSlide]=useState(0)
 useEffect(()=>{const id=setInterval(()=>setSlide(v=>(v+1)%3),6500);return()=>clearInterval(id)},[])
 const filtered=useMemo(()=>products.filter(p=>(active==='TODOS'||p.family===active)&&(!query||`${p.sku} ${p.brand} ${p.description}`.toLowerCase().includes(query.toLowerCase()))&&(gender==='Todos'||p.gender===gender)),[active,query,gender])
 return <main>
  <header className="site-header"><a className="logo" href="#inicio"><img src="/brand/montescano.png" alt="Montescano"/></a><nav className={menu?'open':''}>{[['INICIO','#inicio'],['MONTESCANO','#catalogo'],['VIZANTI','#catalogo'],['VIZANTI KIDS','#catalogo'],['SMART WATCH','#catalogo'],['SETS','#catalogo'],['CORPORATIVO','#corporativo'],['CONTACTO','#contacto']].map(([label,href])=><a key={label} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="header-cta" href="#contacto">SOLICITAR INFORMACIÓN</a><button className="menu-toggle" aria-label="Abrir menú" onClick={()=>setMenu(v=>!v)}>{menu?'×':'☰'}</button></header>
  <section id="inicio" className="hero"><div className="hero-copy"><p className="kicker">MONTESCANO · RELOJERÍA MEXICANA · DESDE 1998</p><h1>{['Precisión que se presenta con claridad.','Colecciones para hacer negocios.','Diseño documentado, listo para descubrir.'][slide]}</h1><p>Una experiencia comercial para conocer Montescano, Vizanti y sus líneas documentadas.</p><div className="hero-actions"><a className="button primary" href="#catalogo">EXPLORAR COLECCIONES <span>→</span></a><a className="button text" href="#corporativo">PROYECTOS CORPORATIVOS <span>↗</span></a></div></div><div className="hero-visual"><img key={slide} src={slide===1?'/catalogo/smartwatch-page1.png':'/catalogo/montescano-page1.png'} alt="Fotografía real de catálogo Montescano"/><div className="hero-counter"><span>0{slide+1}</span><i></i><span>03</span></div></div></section>
  <section id="catalogo" className="catalog-section"><div className="section-intro"><div><p className="kicker">CATÁLOGO COMERCIAL</p><h2>Encuentra el modelo adecuado.</h2></div><p className="section-note">{filtered.length} resultados visibles en esta revisión.<br/>Las referencias pendientes permanecen fuera del catálogo público.</p></div><div className="controls"><div className="category-tabs" role="tablist">{families.map(([name,count])=><button key={name} className={active===name?'active':''} onClick={()=>setActive(name)}><span>{name}</span><small>{count}</small></button>)}</div><div className="search-filter"><label><span>⌕</span><input aria-label="Buscar por modelo o SKU" placeholder="Buscar por modelo o SKU..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Limpiar búsqueda">×</button>}</label><select aria-label="Filtrar por género" value={gender} onChange={e=>setGender(e.target.value)}><option>Todos</option><option>Caballero</option><option>Dama</option><option>Unisex</option><option>Niños</option></select></div></div><div className="product-grid">{filtered.map((p,i)=><article className="product-card" key={p.sku} onClick={()=>setQuick(p)} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&setQuick(p)}><div className="product-media"><img src={p.image} alt={`${p.brand} ${p.sku}, imagen de catálogo`} loading={i>1?'lazy':'eager'}/><span>VER DETALLES <b>↗</b></span></div><p className="product-brand">{p.brand}</p><h3>{p.sku}</h3><p className="product-description">{p.description}</p><small className="source">Fuente trazable · {p.source}</small></article>)}</div>{filtered.length===0&&<div className="empty"><h3>No encontramos ese modelo.</h3><p>Prueba con otro SKU o limpia los filtros.</p><button className="button text" onClick={()=>{setQuery('');setGender('Todos');setActive('TODOS')}}>LIMPIAR FILTROS ↗</button></div>}</section>
  <section className="looking"><div><p className="kicker">DESCUBRE POR INTERÉS</p><h2>¿Qué estás buscando?</h2></div><div className="look-grid">{[['CABALLERO','MONTESCANO'],['DAMA','VIZANTI'],['NIÑOS','KIDS'],['PROYECTOS CORPORATIVOS','CORPORATIVO']].map(([title,target])=><a href={target==='CORPORATIVO'?'#corporativo':'#catalogo'} className="look-card" key={title}><img src="/catalogo/montescano-page1.png" alt="Fotografía real de catálogo"/><span>{title}<b>↗</b></span></a>)}</div></section>
  <section id="corporativo" className="corporate"><div><p className="kicker">INSTITUCIONAL · PERSONALIZACIÓN</p><h2>Proyectos corporativos y personalización.</h2><p>Para empresas, reconocimientos, incentivos, regalos corporativos y proyectos por volumen. La documentación contempla personalización sobre cotización; el alcance se confirma en cada proyecto.</p><a className="button light" href="#contacto">SOLICITAR INFORMACIÓN <span>↗</span></a></div><div className="corporate-mark">M</div></section>
  <footer id="contacto"><div><img src="/brand/montescano.png" alt="Montescano"/><p>Solicita información comercial sobre modelos, colecciones o proyectos especiales.</p></div><a className="button primary" href="mailto:blevy@montescano.com.mx">CONTACTAR POR EMAIL <span>↗</span></a></footer>
  {quick&&<div className="modal-backdrop" role="presentation" onClick={()=>setQuick(null)}><section className="quick-view" role="dialog" aria-modal="true" aria-labelledby="quick-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Cerrar vista rápida" onClick={()=>setQuick(null)}>×</button><div className="quick-image"><img src={quick.image} alt={`${quick.brand} ${quick.sku}`}/></div><div className="quick-info"><p className="kicker">{quick.brand}</p><h2 id="quick-title">{quick.sku}</h2><p>{quick.description}</p><dl><div><dt>Género</dt><dd>{quick.gender}</dd></div><div><dt>Disponibilidad</dt><dd>{quick.availability}</dd></div></dl><small className="source">{quick.source}</small><a className="button primary" href={`mailto:blevy@montescano.com.mx?subject=Información sobre ${quick.sku}`}>SOLICITAR INFORMACIÓN ↗</a></div></section></div>}
 </main>}
